AllYouMedia/AllYouMedia/Areas/Admin/Controllers/SharedController.cs
using AllYouMedia.Areas.Admin.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;
using BusinessEntity.ConcreateEntity;
using AllYouMedia.DataAccess.ServiceLayer;
using AllYouMedia.Code;

namespace AllYouMedia.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin,SuperAdmin")]
    public class SharedController : Controller
    {
        public long AspNetUserID
        {
            get
            {
                long str = -1;
                if (System.Web.HttpContext.Current.Session["AspNetUserID"] != null)
                {
                    str = Convert.ToInt64(System.Web.HttpContext.Current.Session["AspNetUserID"]);
                }
                else
                {
                    str = userService.GetAspNetUserIDByUserName(User.Identity.Name);
                    Session["AspNetUserID"] = str;
                }
                return str;
            }
        }
        private IAspNetUserService userService;
        private IMessageService messageService;
        private ILogService userLogService;
        public SharedController(AspNetUserService userService, MessageService messageService, LogService userLogService)
        {
            this.userService = userService;
            this.messageService = messageService;
            this.userLogService = userLogService;
        }

        #region AdminHeader
        // GET: Shared
        [ChildActionOnly]
        public PartialViewResult AdminLeft()
        {
            return PartialView();
        }

        [ChildActionOnly]
        public PartialViewResult AdminHeader()
        {
            AdminHeaderModel model = new AdminHeaderModel();
            List<MessageModel> Message = new List<MessageModel>();
            var lstMessage = messageService.GetMessagesByUserID(AspNetUserID);
            ViewBag.MessageCount = lstMessage.Count;
            Message = lstMessage.Select(x =>
            {
                return new MessageModel()
                {
                    MailFrom = x.FromAspNetUser.Name + " <<" + x.FromAspNetUser.UserName + ">>",
                    Subject = x.Subject,
                    Message = x.Body,
                    SentDate = x.CreatedOn.ToDateTimeString(),
                };

            }).ToList();
            model.Message = Message;
            List<AdminActivityModel> Activity = null;
            //DataTable dt_Activity = new RoleDataEntity().Role_GetAdminActivityForHeader(AspNetUserID);
            var lstActivity = userLogService.GetUserLogForHeader(AspNetUserID);
            Activity = lstActivity.Select(x =>
            {
                return new AdminActivityModel()
                {
                    Reference = x.Description,
                    Type = x.ActivityType,
                    ActionDate = x.CreatedOn.ToDateTimeString(),
                };

            }).ToList();
            model.Activity = Activity;

            model.Image = "/Images/AdminImage.png";
            return PartialView(model);
        }
        #endregion
    }
}

AllYouMedia/AllYouMedia/Controllers/SharedController.cs
using AllYouMedia.DataAccess.ServiceLayer;
using AllYouMedia.Models;
using BusinessEntity.ConcreateEntity;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;

namespace AllYouMedia.Controllers
{
    [AllowAnonymous]
    public class SharedController : Controller
    {
        List<SubMenuModel> SubMenu = new List<SubMenuModel>();
        public long UserID
        {
            get
            {
                long str = -1;
                if (System.Web.HttpContext.Current.Session["UserID"] != null)
                {
                    str = Convert.ToInt64(System.Web.HttpContext.Current.Session["UserID"]);
                }
                else
                {
                    str = new RoleDataEntity().GetLoggedInUserID(User.Identity.Name);
                    Session["UserID"] = str;
                }
                return str;
            }
        }

        // GET: Shared      
        [ChildActionOnly]
        [Authorize]
        public PartialViewResult UserLeft()
        {
            return PartialView();
        }

        [ChildActionOnly]
        [Authorize]
        public PartialViewResult UserHeader()
        {
            UserHeaderModel model = new UserHeaderModel();
            List<MessageModel> Message = new List<MessageModel>();
            DataTable dt = new MessageDataEntity().Message_Select_InboxForHeader(User.Identity.Name);
            if (dt.Rows.Count > 0)
            {
                ViewBag.MessageCount = dt.Rows[0]["MessageCount"].ToString();
            }
            else
            {
                ViewBag.MessageCount = "0";
            }
            Message = dt.AsEnumerable().Select(x =>
            {
                return new MessageModel()
                {
                    MailFrom = x["Mail From"].ToString(),
                    Subject = x["Subject"].ToString(),
                    Message = x["Message"].ToString(),
                    SentDate = x["Sent Date"].ToString(),
                };

            }).ToList();
            model.Message = Message;

            List<UserActivityModel> Activity = new List<UserActivityModel>();
            DataTable dt_Activity = new RoleDataEntity().Role_GetUserActivityForHeader();
            Activity = dt_Activity.AsEnumerable().Select(x =>
            {
                return new UserActivityModel()
                {
                    Reference = x["Reference"].ToString(),
                    Type = x["Type"].ToString(),
                    ActionDate = x["Action Date"].ToString(),
                };

            }).ToList();
            model.Activity = Activity;

            DataTable dt_image = new RoleDataEntity().Role_Get_UserProfileImage();
            if (dt_image.Rows.Count > 0)
            {
                model.Image = dt_image.Rows[0]["Profile Image"].ToString().Replace("~/", "/");
            }
            else
            {
                model.Image = "/Images/img_128x128.png";
            }

            List<UserFanBaseModel> FanBase = new List<UserFanBaseModel>();
            DataTable dt_FanBase = new RoleDataEntity().Role_GetUserFanBaseRequest();
            FanBase = dt_FanBase.AsEnumerable().Select(x =>
        {
            return new UserFanBaseModel()
            {
                UID = x["UID"].ToString(),
                TalentBUID = x["TalentBUID"].ToString(),
                FanBUID = x["FanBUID"].ToString(),
                ImageUrl = x["FanImage"].ToString().Replace("~/", "/"),
                FanLoginName = x["FanLoginName"].ToString(),
            };

        }).ToList();
            for (var j = 0; j < FanBase.Count; j++)
            {
                string ImageUrl = FanBase[j].ImageUrl.ToString();
                if (ImageUrl == "")
                {
                    FanBase[j].ImageUrl = "/Images/img_128x128.png";
                }
            }
            model.FanBase = FanBase;
            if (dt_FanBase.Rows.Count > 0)
            {
                ViewBag.fanBase = true;
            }
            else
            {
                ViewBag.fanBase = false;
            }

            return PartialView(model);
        }

        [ChildActionOnly]
        public PartialViewResult GuestMenu()
        {
            IndexModel model = new IndexModel();
            List<MenuModel> Menu = new List<MenuModel>();
            DataTable dt_Menu = new DataTable();
            dt_Menu = new MasterDataEntity().Master_Select_CategoryDefaultCondition();
            foreach (DataRow dr in dt_Menu.Rows)
            {
                Menu.Add(new MenuModel
                {
                    UID = dr["UID"].ToString(),
                    Text = dr["Text"].ToString(),
                    Name = dr["Name"].ToString(),
                });
                ViewData["UID"] = dr["UID"].ToString();
                this.GetSubMenu();
            }
            Menu = Menu.OrderBy(x => x.Text).ToList();
            model.Menu = Menu;
            model.SubMenu = SubMenu;
            return PartialView(model);
        }

        public List<SubMenuModel> GetSubMenu()
        {
            if (ViewData["UID"] != null)
            {
                DataTable dt = new DataTable();
                dt = new MasterDataEntity().Master_Select_MainCategoryListWithMenu(ViewData["UID"].ToString());
                foreach (DataRow dr in dt.Rows)
                {
                    SubMenu.Add(new SubMenuModel
                    {
                        UID = dr["UID"].ToString(),
                        Name = dr["Name"].ToString(),
                        MenuUID = dr["MenuUID"].ToString(),
                        AlbumUID = dr["AlbumUID"].ToString(),
                        AlbumName = dr["AlbumName"].ToString(),
                    });
                }
                ViewData["UID"] = null;
                SubMenu = SubMenu.OrderBy(x => x.Name).ToList();
            }
            return SubMenu;
        }

        [ChildActionOnly]
        public PartialViewResult HeaderCart()
        {
            IndexModel model = new IndexModel();
            List<CartModel> Cart = new List<CartModel>();
            DataTable dt_Cart = new ShoppingDataEntity().Shopping_Select_Cart(_CodeClass.GetProductCart(), User.Identity.Name);
            if (dt_Cart.Rows.Count > 0)
            {
                _CodeClass.SetProductCart(dt_Cart);
                foreach (DataRow dr in dt_Cart.Rows)
                {
                    Cart.Add(new CartModel
                    {
                        itemUID = dr["UID"].ToString(),
                        Name = dr["Name"].ToString(),
                        QTY = dr["QTY"].ToString(),
                        IMAGE = dr["Product URL"].ToString().Replace("~/", "/"),
                        Rate = Convert.ToDecimal(dr["Rate"].ToString()),
                    });
                    ViewBag.GrossAmount = _CodeClass.GetCurrency(Convert.ToDecimal(dt_Cart.Rows[0]["Expedited Shipping"]) + Convert.ToDecimal(dt_Cart.Compute("SUM([Net Amount])", "")));
                }
                for (var i = 0; i < Cart.Count; i++)
                {
                    string extFile = System.IO.Path.GetExtension(Cart[i].IMAGE).ToLower();
                    if (extFile == ".mp4" || extFile == ".avi" || extFile == ".wmv")
                    {
                        Cart[i].IMAGE = "/Images/document/mp4.jpg";
                    }
                    else if (extFile == ".pdf")
                    {
                        Cart[i].IMAGE = "/Images/document/.pdf.png";
                    }
                    else if (extFile == ".ppt" || extFile == ".pptx")
                    {
                        Cart[i].IMAGE = "/Images/document/.ppt.png";
                    }
                    else if (extFile == ".doc" || extFile == ".docx")
                    {
                        Cart[i].IMAGE = "/Images/document/.doc.PNG";
                    }
                    else if (extFile == ".xls" || extFile == ".xlsx")
                    {
                        Cart[i].IMAGE = "/Images/document/.xls.PNG";
                    }
                    else if (extFile == ".mp3")
                    {
                        Cart[i].IMAGE = "/Images/document/mp3.jpg";
                    }
                }
            }
            else
            {
                ViewBag.GrossAmount = "$ 0.00";
            }
            model.Cart = Cart;
            return PartialView(model);
        }

        [ChildActionOnly]
        public PartialViewResult Product()
        {
            IndexModel model = new IndexModel();
            List<MenuModel> Menu = new List<MenuModel>();
            DataTable dt_Menu = new DataTable();
            dt_Menu = new MasterDataEntity().Master_Select_CategoryDefaultCondition();
            foreach (DataRow dr in dt_Menu.Rows)
            {
                Menu.Add(new MenuModel
                {
                    UID = dr["UID"].ToString(),
                    Text = dr["Text"].ToString(),
                    Name = dr["Name"].ToString(),
                });
            }
            Menu = Menu.OrderBy(x => x.Text).ToList();
            model.Menu = Menu;
            return PartialView(model);
        }
    }

    [Authorize]
    public class SharedAuthController : Controller
    {
        private IAspNetUserService aspNetUserSerivce;
        private ISubCategoryService subCategoryService;
        private IItemService itemService;
        private IOrderService orderService;
        private IPayoutDistributionService payoutDistributionService;

        public SharedAuthController(AspNetUserService aspNetUserSerivce, SubCategoryService subCategoryService, ItemService itemService, OrderService orderService, PayoutDistributionService payoutDistributionService)
        {
            this.aspNetUserSerivce = aspNetUserSerivce;

AllYouMedia/AllYouMedia/Areas/Admin/Views/Shared/AdminLeft.cshtml
@*<aside id="sidebar" class="material-menu">
    <div class="material-left-back"></div>
    <div id="material_navbar" class="material_navbar">
        <div class="material_navbar_content">
            <form class="material_navbar_form" style="border-bottom: 1px solid rgba(255, 255, 255, 0.1);">
                <div class="hamburger hamburger--emphatic">
                    <div class="hamburger-box">
                        <div class="hamburger-inner"></div>
                    </div>
                </div>
                <div class="sidebar-search">
                    <input id="live-search-box" type="search" class="form-control input-sm" placeholder="Search...">
                    <a href="javascript:void(0)"><i class="search-close icon_search"></i></a>
                </div>
            </form>
            <div class="sidebar-menu">
                <ul class="main-menu nav site-menu live-search-list" id="site-menu" data-plugin="custom-scroll"
                    data-suppress-scroll-x="true" data-height="100%">
                    <li class="sub-item">
                        <a href="@Url.Action("Index", "Admin")" class="flat-buttons">
                            <span class="icon_desktop header-icon material-icon"
                                  aria-hidden="true"></span>DASHBOARD
                        </a>
                    </li>
                    <li class="sub-item">
                        <a href="@Url.Action("ChangePassword", "Admin")" class="flat-buttons">
                            <span class="icon_key header-icon material-icon"
                                  aria-hidden="true"></span>CHANGE PASSWORD
                        </a>
                    </li>
                    <li class="sub-item">
                        <a href="@Url.Action("Distributor", "Admin")" class="flat-buttons">
                            <span class="icon_bag header-icon material-icon"
                                  aria-hidden="true"></span>DISTRIBUTOR
                        </a>
                    </li>
                    <li class="sub-item">
                        <a href="@Url.Action("Membership", "Admin")" class="flat-buttons">
                            <span class="icon_shield header-icon material-icon"
                                  aria-hidden="true"></span>MEMBERSHIP REPORT
                        </a>
                    </li>
                    <li class="sub-item">
                        <a href="javascript:void(0)" class="flat-buttons">
                            <span class="icon_profile header-icon material-icon"
                                  aria-hidden="true"></span>AREA PROMOTER
                            <span class="float-xs-right"><i class="icon_plus"></i></span>
                        </a>
                        <ul class="sub-menu">
                            <li>
                                <a class="flat-buttons" href="@Url.Action("AddMediaPromoter", "Admin")">ADD</a>
                            </li>
                            <li>
                                <a class="flat-buttons" href="@Url.Action("GenerateCode", "Admin")">Code</a>
                            </li>
                        </ul>
                    </li>
                    <li class="sub-item">
                        <a href="javascript:void(0)" class="flat-buttons">
                            <span class="icon_grid-2x2 header-icon material-icon"
                                  aria-hidden="true"></span>PRODUCT
                            <span class="float-xs-right"><i class="icon_plus"></i></span>
                        </a>
                        <ul class="sub-menu">
                            <li>
                                <a class="flat-buttons" href="@Url.Action("AddProduct", "Admin")">ADD PRODUCT</a>
                            </li>
                            <li>
                                <a class="flat-buttons" href="@Url.Action("CategoryManagement", "Admin")">CATEGORY Mgmt.</a>
                            </li>
                            <li>
                                <a class="flat-buttons" href="@Url.Action("SubCategoryManagement", "Admin")">SubCATEGORY Mgmt.</a>
                            </li>
                            <li>
                                <a class="flat-buttons" href="@Url.Action("SuggestCategory", "Admin")">SUGGESTED CATEGORY</a>
                            </li>
                            <li>
                                <a class="flat-buttons" href="@Url.Action("PurchaseHistory", "Admin")">PURCHASE HISTORY</a>
                            </li>
                        </ul>
                    </li>
                    <li class="sub-item">
                        <a href="javascript:void(0)" class="flat-buttons">
                            <span class="icon_house header-icon material-icon"
                                  aria-hidden="true"></span>TEAM
                            <span class="float-xs-right"><i class="icon_plus"></i></span>
                        </a>
                        <ul class="sub-menu">
                            <li>
                                <a class="flat-buttons" href="@Url.Action("GeneologyLevel", "Admin")">Geneology Level</a>
                            </li>
                            <li>
                                <a class="flat-buttons" href="@Url.Action("GeneologyDownline", "Admin")">Geneology Downline</a>
                            </li>
                        </ul>
                    </li>
                    <li class="sub-item">
                        <a href="@Url.Action("Message", "Admin")" class="flat-buttons">
                            <span class="icon_mail header-icon material-icon"
                                  aria-hidden="true"></span>MESSAGE<span class="tag tag-pill tag-success float-xs-right">@Convert.ToString(new BusinessEntity.ConcreateEntity.MasterDataEntity().GetTalentUnreadMessage())</span>
                            </a>
                        </li>
                        <li class="sub-item">
                            <a href="@Url.Action("Control", "Admin")" class="flat-buttons">
                                <span class="icon_compass header-icon material-icon"
                                      aria-hidden="true"></span>CONTROL
                            </a>
                        </li>
                        <li class="sub-item">
                            <a href="@Url.Action("PageManagement", "Admin")" class="flat-buttons">
                                <span class="icon_pencil-edit header-icon material-icon"
                                      aria-hidden="true"></span>PAGE MANAGEMENT
                            </a>
                        </li>
                        <li class="sub-item">
                            <a href="javascript:void(0)" class="flat-buttons">
                                <span class="icon_cog header-icon material-icon"
                                      aria-hidden="true"></span>EVENT
                                <span class="float-xs-right"><i class="icon_plus"></i></span>
                            </a>
                            <ul class="sub-menu">
                                <li>
                                    <a class="flat-buttons" href="@Url.Action("Event", "Admin")">EVENT</a>
                                </li>
                                <li>
                                    <a class="flat-buttons" href="@Url.Action("EventPerformer", "Admin")">PERFORMER</a>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </aside>*@



<!-- Content Wrapper. Contains page content -->

AllYouMedia/AllYouMedia/Areas/Admin/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html ng-app="Admin">
<head>
    <meta charset="utf-8">
    <meta name="description" content="bootstrap default admin template">
    <meta name="viewport" content="width=device-width">
    <link rel="shortcut icon" type="image/x-icon" href="~/Images/Round-Logo.png">  
    <link href="~/Content/bootstrap.css" rel="stylesheet" />   
    <link href="~/assets/global/plugins/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/assets/icons_fonts/elegant_font/elegant.css" rel="stylesheet" />
    <link href="~/assets/layouts/layout-material-menu/css/color/light/color-default.css" rel="stylesheet" />
    <link href="~/assets/global/plugins/switchery/dist/switchery.min.css" rel="stylesheet" />
    <link href="~/assets/global/plugins/perfect-scrollbar/css/perfect-scrollbar.min.css" rel="stylesheet" />
    <link href="~/assets/global/plugins/css-hamburgers/dist/hamburgers.css" rel="stylesheet" />
    <link href="~/assets/global/plugins/font-awesome/css/font-awesome.min.css" rel="stylesheet" />
    <link href="~/assets/global/plugins/morris.js/morris.min.css" rel="stylesheet" />
    <link href="~/assets/global/plugins/owl.carousel/dist/assets/owl.carousel.min.css" rel="stylesheet" />
    <link href="~/assets/global/plugins/owl.carousel/dist/assets/owl.theme.default.min.css" rel="stylesheet" />
    <link href="~/assets/global/plugins/jqvmap/dist/jqvmap.min.css" rel="stylesheet" />
    <link href="~/assets/global/plugins/chartist/dist/chartist.min.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-timepicker.css" rel="stylesheet" />
    <link href="~/Content/datepicker.css" rel="stylesheet" />
    <link href="~/assets/global/plugins/flatpickr/dist/flatpickr.min.css" rel="stylesheet" />
    <link href="~/assets/global/plugins/filament-tablesaw/dist/tablesaw.min.css" rel="stylesheet" />
    <link href="~/assets/global/plugins/jstree/dist/themes/default/style.css" rel="stylesheet" />
    <link href="~/Content/sweetalert.css" rel="stylesheet" />
    <link href="~/assets/global/css/components.css" rel="stylesheet" />
    <link href="~/assets/layouts/layout-material-menu/css/layout.css" rel="stylesheet" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <div class="wrapper">
        @{Html.RenderAction("AdminHeader", "Shared");}
        <section id="main" class="container-fluid">
            <div class="row">
                @{Html.RenderAction("AdminLeft", "Shared");}
                <section id="content-wrapper" class="form-elements">
                    <div class="site-content-title">
                        <div class="col-md-1 col-sm-1 col-xs-12">                         
                        </div>
                        <div class="col-md-5 col-sm-5 col-xs-12">
                            <h2 class="float-xs-left content-title-main">@ViewBag.Title</h2>
                        </div>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <h2 class="float-xs-right content-title-main">Hi.. @User.Identity.Name.ToUpper()</h2>
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="col-md-12">
                            <div class="col-md-12">
                                <div class="col-md-12">
                                    <div class="col-md-12">
                                        @Html.Raw(TempData["Message"])
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="contain-inner dashboard-v3">
                        <div class="row">
                            @RenderBody()
                        </div>
                    </div>
                </section>
            </div>
        </section>
        <footer id="footer">
            Copyright&copy; 2017, All Rights Reserved.
        </footer>
    </div>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
    <script src="~/Scripts/jquery-1.10.2.js"></script>
    <!-- START CORE JAVASCRIPT -->
    <script type="text/javascript" src="~/assets/global/plugins/jquery/dist/jquery.min.js"></script>
    <script type="text/javascript" src="~/assets/global/plugins/tether/dist/js/tether.min.js"></script>
    <script type="text/javascript" src="~/assets/global/plugins/bootstrap/dist/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="~/assets/global/plugins/perfect-scrollbar/js/perfect-scrollbar.jquery.min.js"></script>
    <script type="text/javascript" src="~/assets/global/plugins/switchery/dist/switchery.min.js"></script>
    <script type="text/javascript" src="~/assets/global/plugins/screenfull.js/dist/screenfull.min.js"></script>
    <script type="text/javascript" src="~/assets/global/plugins/Waves/dist/waves.min.js"></script>
    <script src="~/assets/global/plugins/ModalWindowEffects/js/classie.js"></script>
    <!-- END CORE JAVASCRIPT -->
    <!-- START PAGE PLUGINS -->
    <script type="text/javascript" src="~/assets/global/plugins/chartist/dist/chartist.min.js"></script>
    <script type="text/javascript" src="~/assets/global/plugins/arcseldon-jquery.sparkline/dist/jquery.sparkline.js"></script>
    <script type="text/javascript" src="~/assets/global/plugins/raphael/raphael.min.js"></script>
    <script type="text/javascript" src="~/assets/global/plugins/morris.js/morris.min.js"></script>
    <script type="text/javascript" src="~/assets/global/plugins/owl.carousel/dist/owl.carousel.min.js"></script>
    <script type="text/javascript" src="~/assets/global/plugins/jqvmap/dist/jquery.vmap.min.js"></script>
    <script type="text/javascript" src="~/assets/global/plugins/jqvmap/dist/maps/jquery.vmap.world.js"></script>
    <script type="text/javascript" src="~/assets/global/plugins/jqvmap/examples/js/jquery.vmap.sampledata.js"></script>
    <script type="text/javascript" src="~/assets/global/plugins/waypoints/lib/jquery.waypoints.min.js"></script>
    <script type="text/javascript" src="~/assets/global/plugins/Counter-Up/jquery.counterup.js"></script>
    <script type="text/javascript" src="~/assets/global/plugins/raphael/raphael.min.js"></script>
    <!-- END PAGE PLUGINS -->
    <!-- START GLOBAL JAVASCRIPT -->
    <script src="~/Scripts/jQuery.print.js"></script>
    <script src="~/assets/global/plugins/jstree/dist/jstree.js"></script>
    <script src="~/Scripts/bootstrap-datepicker.js"></script>
    <script src="~/Scripts/bootstrap-timepicker.js"></script>
    <script type="text/javascript" src="~/assets/global/plugins/flatpickr/dist/flatpickr.min.js"></script>
    <script type="text/javascript" src="~/assets/global/js/site.min.js"></script>
    <script type="text/javascript" src="~/assets/global/js/site-settings.min.js"></script>
    <!-- END GLOBAL JAVASCRIPT -->
    <!-- START PAGE JAVASCRIPT -->
    <script src="~/assets/global/plugins/filament-tablesaw/dist/tablesaw.js"></script>
    <script src="~/assets/global/plugins/filament-tablesaw/dist/tablesaw-init.js"></script>
    <script src="~/assets/global/js/global/treeview.js"></script>
    <script type="text/javascript" src="~/assets/global/js/global/dashboard_v3.min.js"></script>
    <script src="~/assets/global/js/global/invoice.js"></script>
    <script src="~/assets/global/js/global/invoice.min.js"></script>
    <script src="~/Scripts/sweetalert-dev.js"></script>
    <!-- END PAGE JAVASCRIPT -->
    <!-- START THEME LAYOUT JAVASCRIPT -->
    <script type="text/javascript" src="~/assets/layouts/layout-material-menu/js/layout.js"></script>
    <script type="text/javascript">
        $('.time').timepicker({
            'minTime': '11:00am',
            'maxTime': '11:00pm',
            'showDuration': true
        });
    </script>
    <script type="text/javascript">
        $('.datepicker').datepicker({
            autoclose: true,
            todayHighlight: true
        });
    </script>

    @RenderSection("scripts", required: false)
</body>

</html>