AllYouMedia/AllYouMedia/Areas/Admin/Controllers/LogonController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AllYouMedia.Areas.Admin.Models;
using DataLayer;
using System.Web.Security;
using BusinessEntity.ConcreateEntity;
using Microsoft.AspNet.Identity;
using AllYouMedia.Models;
using Microsoft.AspNet.Identity.EntityFramework;
using System.Threading.Tasks;
using Microsoft.Owin.Security;
using AllYouMedia.DataAccess.DataLayer;
using AllYouMedia.DataAccess.ServiceLayer;
using AllYouMedia.DataAccess.EntityLayer.DBEntity;

namespace AllYouMedia.Areas.Admin.Controllers
{
    public class LogonController : Controller
    {
        private IAspNetUserService userService;
        //public LogonController()
        //    : this(new AspNetUserManager(new UserStore<AspNetUser, AspNetRole, long, AspNetUserLogin, AspNetUserRole, AspNetUserClaim>(new DataContext())))
        //{
        //    userService = _userService;
        //}

        public LogonController(AspNetUserManager userManager, AspNetUserService _userService)
        {
            UserManager = userManager;
            userService = _userService;
        }

        public AspNetUserManager UserManager { get; private set; }
        private IAuthenticationManager AuthenticationManager
        {
            get
            {
                return HttpContext.GetOwinContext().Authentication;
            }
        }
        public JsonResult RegisterAdmin()
        {
            var userName="admin@allyoumedia.com";
            var result = UserManager.Create(new AspNetUser
            {
                PasswordOrignal = "12345678",
                UserName = userName,
                CreatedOn = DateTime.Now,
                Email = userName,
                EmailConfirmed = true,
                IsActive = true,
                Name = "Admin",
            }, "12345678");
            if (result.Succeeded)
            {
                var user=UserManager.FindByName(userName);
                UserManager.AddToRole(user.Id, "Admin");
                return Json(new { Result = "OK" }, JsonRequestBehavior.AllowGet);
            }
            else
                return Json(new { Result = "ERROR", Message = string.Join("|", result.Errors) }, JsonRequestBehavior.AllowGet);
        }
        // GET: Admin/AdminLogin
        [AllowAnonymous]
        public ActionResult Index()
        {
            return View();
        }

        [AllowAnonymous]
        [HttpPost]
        public async Task<ActionResult> Index(LoginModel model, string returnUrl)
        {
            if (ModelState.IsValid)
            {
                var user = await UserManager.FindAsync(model.LoginID, model.LoginPassword);
                if (user != null)
                {
                    if (UserManager.IsInRole(user.Id, "Admin"))
                    {
                        var userInternalTupple = userService.UserLoginChecknUpdate(model.LoginID, Request.UserHostAddress);
                        if (userInternalTupple.Item1 == null)
                        {
                            await SignInAsync(user, model.RememberMe);
                            return RedirectToLocal(returnUrl);
                        }
                        else ModelState.AddModelError("", userInternalTupple.Item1);
                    }
                    else
                        ModelState.AddModelError("", "Unauthorized! Your are not a admin.");
                }
                else
                {
                    ModelState.AddModelError("", "Invalid username or password.");
                }
            }
            return View(model);
        }
        private async Task SignInAsync(AspNetUser user, bool isPersistent)
        {
            AuthenticationManager.SignOut(DefaultAuthenticationTypes.ExternalCookie);
            var identity = await UserManager.CreateIdentityAsync(user, DefaultAuthenticationTypes.ApplicationCookie);
            AuthenticationManager.SignIn(new AuthenticationProperties() { IsPersistent = isPersistent }, identity);
        }
        private ActionResult RedirectToLocal(string returnUrl)
        {
            if (Url.IsLocalUrl(returnUrl))
            {
                return Redirect(returnUrl);
            }
            else
            {
                return RedirectToAction("Index", "Admin");
            }
        }
    }
}

AllYouMedia/AllYouMedia/Areas/Admin/Views/Logon/Index.cshtml
@model AllYouMedia.Areas.Admin.Models.LoginModel
@using System.Web.Mvc;
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>AllYouMedia | @ViewBag.Title</title>
    <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
    <link rel="shortcut icon" type="image/x-icon" href="/Content/AdminLTE/Images/faviocn.ico">
    <!-- Bootstrap 3.3.2 -->
    <link href="/Content/AdminLTE/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <!-- Font Awesome Icons -->
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
    <!-- Theme style -->
    <link href="/Content/AdminLTE/dist/css/AdminLTE.min.css" rel="stylesheet" type="text/css" />
    <!-- iCheck -->
    <link href="/Content/AdminLTE/plugins/iCheck/square/blue.css" rel="stylesheet" type="text/css" />
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
    <style>
        .parsley-errors-list li, .validation-summary-errors ul li {
            color: red;
        }        
    </style>
</head>
<body class="login-page">
    <div class="login-box">
        <div class="login-logo">
            <a href="/"><img src="/Images/new_logo1.png" style="width:100%;" /></a>
        </div><!-- /.login-logo -->
        <div class="login-box-body">
            <p class="login-box-msg">Sign in to start your session</p>
            @using (Html.BeginForm("Index", "Logon", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { role = "form", data_parsley_validate = "" }))
            {
                <div class="form-group has-feedback">
                    @Html.TextBoxFor(model => model.LoginID, new { placeholder = "Enter Login ID", maxlenghth = "50", @class = "form-control", required = "" })
                    @Html.ValidationMessageFor(model => model.LoginID)
                    <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
                </div>
                <div class="form-group has-feedback">
                    @Html.PasswordFor(model => model.LoginPassword, new { placeholder = "Enter Password", @class = "form-control", required = "" })
                    <span class="glyphicon glyphicon-lock form-control-feedback"></span>
                    @Html.ValidationMessageFor(model => model.LoginPassword)
                </div>
                <div class="row">
                    <div class="col-xs-8">
                        <div class="checkbox icheck">
                            <label>
                                <input type="checkbox" name="RememberMe"> Remember Me
                            </label>
                        </div>
                    </div><!-- /.col -->
                    <div class="col-xs-4">
                        <button type="submit" class="btn btn-primary btn-block btn-flat">Sign In</button>
                    </div><!-- /.col -->
                </div>
                @Html.ValidationSummary(false)
                if (TempData["Error"] != null)
                {
                    <div class='alert alert-danger alert-dismissable' role='alert'>
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                        <h4>Alert!</h4>
                        @TempData["Error"]
                    </div>
                }
            }
            <a href="#">I forgot my password</a><br>
        </div><!-- /.login-box-body -->
    </div><!-- /.login-box -->
    <!-- jQuery 2.1.3 -->
    <script src="/Content/AdminLTE/plugins/jQuery/jQuery-2.1.3.min.js"></script>
    <!-- Bootstrap 3.3.2 JS -->
    <script src="/Content/AdminLTE/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
    <!-- iCheck -->
    <script src="/Content/AdminLTE/plugins/iCheck/icheck.min.js" type="text/javascript"></script>
    <script src="~/Scripts/parsley.min.js"></script>
    <script>
        $(function () {
            $('input').iCheck({
                checkboxClass: 'icheckbox_square-blue',
                radioClass: 'iradio_square-blue',
                increaseArea: '20%' // optional
            });
        });
    </script>
</body>
</html>